apiVersion: v1
kind: ServiceAccount
metadata:
  name: %SERVICE_NAME%-service-account
  namespace: %KUBERNETES_NAMESPACE%
  annotations:
    azure.workload.identity/client-id: %STORAGE_IDENTITY_CLIENT_ID%